name: Deploy to VM
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v1
      - name: Build Nextjs app
        uses: actions/setup-node@v1
        with:
          node-version: 12
        run: npm install -g yarn
        run: yarn install --frozen-lockfile
        run: yarn build
      - name: RSync Deployment
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --exclude="" --include="" --filter=""
          path: ./
          remote_path: /var/www/lenaebner/
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
