name: Deploy to VM
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v1
      - name: Build Nextjs app
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
#       - name: RSync Deployment
      - name: Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/var/www/lenaebner/
#         uses: burnett01/rsync-deployments@4.1
#         with:
#           switches: -avzr --delete --exclude="" --include="" --filter=""
#           path: ./
#           remote_path: /var/www/lenaebner.com/
#           remote_host: ${{ secrets.DEPLOY_HOST }}
#           remote_port: ${{ secrets.DEPLOY_PORT }}
#           remote_user: ${{ secrets.DEPLOY_USER }}
#           remote_key: ${{ secrets.DEPLOY_KEY }}
